version: "3.8"
services:
  prowlarr:
    restart: unless-stopped
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    volumes:
      - /home/rick/docker/prowlarr/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
networks: {}
