plugin: community.general.proxmox
url: https://192.168.1.6:8006
validate_certs: false
user: api@pve
token_id: ansible
token_secret: 13127472-e284-41a4-9a05-3c370876b59b
want_facts: true
want_proxmox_nodes_ansible_host: true
#compose:
#  ansible_host: proxmox_ipconfig0.ip | default(proxmox_net0.ip) | ipaddr('address')
