plugin: community.zabbix.zabbix_inventory
server_url: http://192.168.1.99
login_user: Admin
login_password: 'R8sYCikaZN4za3h$BE*H'
host_zapi_query:
  selectApplications: ['name', 'applicationid']
  selectParentTemplates: ['name']
  selectGroups: ['name']
validate_certs: false
groups:
  zbx_enabled: zbx_status == "0"
  zbx_disabled: zbx_status == "1"
  Debian: "'ansible.Debian' in (zbx_groups | join)"
  zbx_Ansible: "'ansible' in (zbx_groups | join)"
  NoAnsible: "'ansible' not in (zbx_groups | join)"
  Dropbear: "'ansible.Dropbear' in (zbx_groups | join)"
  nopython: "'ansible.NoPython' in (zbx_groups | join)"
  Routers: "'ansible.Routers' in (zbx_groups | join)"
  MultiMedia: "'Multimedia' in (zbx_groups | join)"
  kodi: "'Kodi' in (zbx_groups | join)"