version: "3"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    environment:
      WATCHTOWER_SCHEDULE: "0 0 0 * * *"
      TZ: "Europe/Amsterdam"
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_DEBUG: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
