version: "3.8"
services:
  flaresolverr:
    restart: unless-stopped
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - ${PORT:-8191}:8191
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Amsterdam
networks: {}
